---
apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
  namespace: test-namespace
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container

---
apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod-2
  namespace: demo-namespace
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container-2
